language: python

services:
  - docker

script:
  - docker build -t aidmax/terraform-gcp-k8s .

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker tag "aidmax/terraform-gcp-k8s" "aidmax/terraform-gcp-k8s:latest"

deploy:
  provider: script
  script: docker push "aidmax/terraform-gcp-k8s:latest"
