language: python

services:
  - docker

script:
  - docker build -t aidmax/terraform-gcp-k8s .

after_script:
  - docker images

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  - docker tag "aidmax/terraform-gcp-k8s" "aidmax/terraform-gcp-k8s:latest"

deploy:
  provider: script
  script: docker push "aidmax/terraform-gcp-k8s:latest"
